### ISSUE TITLE
Flex board incorrect pinout

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/koruza-hs-boards#1]
Flexible PCB has incorrect pinout, an error occurred while mirroring. High-speed lines are correct, however other signal pins are swapped on either side (note one side has 4 traces after ground, the other 3 traces after ground.)

**Comment by VojislavM** [comment]
Mirroring of the signals will be done on the rigid high speed board of the Koruza unit.

**Comment by VojislavM** [comment]
fixed in the new version of the board:
* [koruza-hs-flex](https://github.com/IRNAS/koruza-hs-flex)
