### ISSUE TITLE
Flex board soldering improvements

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/koruza-hs-boards#2]
The current design of the flexible board is impossible to solder and thus the following changes need to be made:

 1. Solder pads on flex PCB must be half the length of the ones in rigid PCB, covering only half of them
 2. Ground plane should be only half way on the back side of soldering pads, such that you can se though the PCB to align the pads
3. Mounting holes are not exact, so can not be used for alignment, but screwing a holder across improves things significantly.

**Comment by VojislavM** [comment]
Because of the new way to connect SFP modules, this is not the issue anymore. Check the repos:
* [koruza-hs-flex](https://github.com/IRNAS/koruza-hs-flex)
* [koruza-hs-rigid](https://github.com/IRNAS/koruza-hs-rigid)
